project:
  type: website
  output-dir: docs

website:
  title: "Ethan Saline's Portfolio"

  navbar:
    background: light
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Machine Learning"
        file: machine_learning.qmd
      - text: "Time Series"
        file: time_series.qmd
      - text: "Statistical Analysis"
        file: statistical_analysis.qmd
      - text: "Bioinformatics"
        file: bioinformatics.qmd
      - text: "Storytelling"
        file: storytelling.qmd

  page-footer:
    border: true
    left: "Ethan Saline Â© 2026"

format:
  html:
    theme: cerulean
    highlight: tango
    css: styles.css
    toc: true
    code-fold: true
    self-contained: false
