project:
  type: website
  output-dir: docs

website:
  title: "<span style='font-family: Arial Black, Impact, sans-serif;
                     font-weight: 600;
                     font-size: 25px;'>
          Ethan Saline
        </span>"

  navbar:
    background: light
    search: true
    fixed: top
    left:
      - text: "Resume"
        file: resume.qmd
        
      - text: "Machine Learning"
        menu:
          - text: "Overview"
            file: machine_learning.qmd
          - text: "Covid Chest X-Rays CNN"
            file: machine_learning/cnn.qmd
          - text: "Shopping Cart Recomender"
            file: machine_learning/recomend.qmd
            
      - text: "Time Series"
        menu:
          - text: "Overview"
            file: time_series.qmd
          - text: "Consumer Loans Decomposition"
            file: time_series/loans.qmd
          - text: "Influenza-like Illness Decomposition"
            file: time_series/flu.qmd
          - text: "Retail Sales Forecasting"
            file: time_series/retail.qmd
          - text: "Hospital Admissions Forecast"
            file: time_series/hospital.qmd            
            
      - text: "Statistical Analysis"
        menu:
          - text: "Overview"
            file: statistical_analysis.qmd
          - text: "Cardiac Mortality"
            file: statistical_analysis/cardiac.qmd
            
      - text: "Bioinformatics"
        menu:
          - text: "Overview"
            file: bioinformatics.qmd
          - text: "Covid-19"
            file: bioinformatics/covid.qmd
            
      - text: "Agentic AI"
        menu:
          - text: "Overview"
            file: agentic_ai.qmd
          - text: "Senator Stock"
            file: agentic_ai/senator.qmd

  page-footer:
    border: true
    left: "Ethan Saline Â© 2026"

format:
  html:
    theme: cerulean
    highlight: tango
    css: styles.css
    toc: true
    code-fold: true
    self-contained: false
